# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 17:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('muralifpb', '0004_auto_20160410_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(default='', verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='newsportals',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do portal de notícia'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='usermy',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='usermy',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usermy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='usermy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Está ativo?'),
        ),
        migrations.AlterField(
            model_name='usermy',
            name='is_reitoria',
            field=models.BooleanField(default=False, verbose_name='É da reitoria?'),
        ),
        migrations.AlterField(
            model_name='usermy',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='É da equipe administrativa?'),
        ),
        migrations.AlterField(
            model_name='usermy',
            name='matricula',
            field=models.CharField(max_length=30, unique=True, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='usermy',
            name='name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='usermy',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$', 32), 'O nome de usuário só pode conter letras, digitos ou os seguintes caracteres: @/./+/-/_', 'invalid')], verbose_name='Nome de Usuário'),
        ),
    ]
